# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import jobs_pb2 as jobs__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jobs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class JobServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterEngine = channel.unary_unary(
                '/mapreduce.JobService/RegisterEngine',
                request_serializer=jobs__pb2.RegisterEngineRequest.SerializeToString,
                response_deserializer=jobs__pb2.RegisterEngineReply.FromString,
                _registered_method=True)
        self.FetchJob = channel.unary_unary(
                '/mapreduce.JobService/FetchJob',
                request_serializer=jobs__pb2.FetchJobRequest.SerializeToString,
                response_deserializer=jobs__pb2.FetchJobReply.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/mapreduce.JobService/ReportResult',
                request_serializer=jobs__pb2.ReportResultRequest.SerializeToString,
                response_deserializer=jobs__pb2.ReportResultReply.FromString,
                _registered_method=True)


class JobServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterEngine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FetchJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterEngine': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterEngine,
                    request_deserializer=jobs__pb2.RegisterEngineRequest.FromString,
                    response_serializer=jobs__pb2.RegisterEngineReply.SerializeToString,
            ),
            'FetchJob': grpc.unary_unary_rpc_method_handler(
                    servicer.FetchJob,
                    request_deserializer=jobs__pb2.FetchJobRequest.FromString,
                    response_serializer=jobs__pb2.FetchJobReply.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=jobs__pb2.ReportResultRequest.FromString,
                    response_serializer=jobs__pb2.ReportResultReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mapreduce.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mapreduce.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterEngine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapreduce.JobService/RegisterEngine',
            jobs__pb2.RegisterEngineRequest.SerializeToString,
            jobs__pb2.RegisterEngineReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FetchJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapreduce.JobService/FetchJob',
            jobs__pb2.FetchJobRequest.SerializeToString,
            jobs__pb2.FetchJobReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mapreduce.JobService/ReportResult',
            jobs__pb2.ReportResultRequest.SerializeToString,
            jobs__pb2.ReportResultReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
