# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: jobs.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'jobs.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\njobs.proto\x12\tmapreduce\"J\n\x15RegisterEngineRequest\x12\x11\n\tengine_id\x18\x01 \x01(\t\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61pacity\x18\x03 \x01(\x05\"7\n\x13RegisterEngineReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x0f\x46\x65tchJobRequest\x12\x11\n\tengine_id\x18\x01 \x01(\t\"A\n\x07MapTask\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x10\n\x08shard_id\x18\x02 \x01(\x05\x12\x14\n\x0ctext_content\x18\x03 \x01(\t\":\n\nReduceTask\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x0c\n\x04word\x18\x02 \x01(\t\x12\x0e\n\x06\x63ounts\x18\x03 \x03(\x05\"t\n\rFetchJobReply\x12\x11\n\ttask_type\x18\x01 \x01(\t\x12$\n\x08map_task\x18\x02 \x01(\x0b\x32\x12.mapreduce.MapTask\x12*\n\x0breduce_task\x18\x03 \x01(\x0b\x32\x15.mapreduce.ReduceTask\"(\n\tMapOutput\x12\x0c\n\x04word\x18\x01 \x01(\t\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\"\xab\x01\n\x13ReportResultRequest\x12\x11\n\tengine_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x11\n\ttask_type\x18\x03 \x01(\t\x12\x10\n\x08shard_id\x18\x04 \x01(\x05\x12)\n\x0bmap_outputs\x18\x05 \x03(\x0b\x32\x14.mapreduce.MapOutput\x12\x0c\n\x04word\x18\x06 \x01(\t\x12\x13\n\x0btotal_count\x18\x07 \x01(\x05\"5\n\x11ReportResultReply\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xf0\x01\n\nJobService\x12R\n\x0eRegisterEngine\x12 .mapreduce.RegisterEngineRequest\x1a\x1e.mapreduce.RegisterEngineReply\x12@\n\x08\x46\x65tchJob\x12\x1a.mapreduce.FetchJobRequest\x1a\x18.mapreduce.FetchJobReply\x12L\n\x0cReportResult\x12\x1e.mapreduce.ReportResultRequest\x1a\x1c.mapreduce.ReportResultReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'jobs_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERENGINEREQUEST']._serialized_start=25
  _globals['_REGISTERENGINEREQUEST']._serialized_end=99
  _globals['_REGISTERENGINEREPLY']._serialized_start=101
  _globals['_REGISTERENGINEREPLY']._serialized_end=156
  _globals['_FETCHJOBREQUEST']._serialized_start=158
  _globals['_FETCHJOBREQUEST']._serialized_end=194
  _globals['_MAPTASK']._serialized_start=196
  _globals['_MAPTASK']._serialized_end=261
  _globals['_REDUCETASK']._serialized_start=263
  _globals['_REDUCETASK']._serialized_end=321
  _globals['_FETCHJOBREPLY']._serialized_start=323
  _globals['_FETCHJOBREPLY']._serialized_end=439
  _globals['_MAPOUTPUT']._serialized_start=441
  _globals['_MAPOUTPUT']._serialized_end=481
  _globals['_REPORTRESULTREQUEST']._serialized_start=484
  _globals['_REPORTRESULTREQUEST']._serialized_end=655
  _globals['_REPORTRESULTREPLY']._serialized_start=657
  _globals['_REPORTRESULTREPLY']._serialized_end=710
  _globals['_JOBSERVICE']._serialized_start=713
  _globals['_JOBSERVICE']._serialized_end=953
# @@protoc_insertion_point(module_scope)
